"""Instance manifests: the secret side of a gauntlet run.

A manifest is JSONL, one record per holdout task instance. It is generated by
the private side (never the evaluated agent) from a seed, and it holds enough
fingerprint detail for `guard` to detect leaks WITHOUT being given the raw
task files at scan time.

Treat manifest files as private keys: readable by the grader side only.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, replace
from datetime import UTC, datetime
from pathlib import Path

from .fingerprint import SHINGLE_WORDS, normalize, sha256_hex, shingle_set


@dataclass(frozen=True)
class InstanceRecord:
    instance: str
    seed: str
    created: str
    retired: bool
    full_sha256: str
    normalized: str  # kept so guard can find substrings; NEVER print this
    shingles: frozenset[str]
    shingle_words: int


def add_instance(
    manifest_path: Path,
    instance_id: str,
    seed: str,
    files: list[Path],
) -> InstanceRecord:
    blob = "\n".join(f.read_text(encoding="utf-8", errors="replace") for f in files)
    norm = normalize(blob)
    rec = InstanceRecord(
        instance=instance_id,
        seed=seed,
        created=datetime.now(UTC).isoformat(timespec="seconds"),
        retired=False,
        full_sha256=sha256_hex(blob.encode()),
        normalized=norm,
        shingles=frozenset(shingle_set(norm)),
        shingle_words=SHINGLE_WORDS,
    )
    _append(manifest_path, rec)
    return rec


def load_manifest(manifest_path: Path) -> list[InstanceRecord]:
    records = []
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            d = json.loads(line)
            records.append(
                InstanceRecord(
                    instance=d["instance"],
                    seed=d["seed"],
                    created=d["created"],
                    retired=bool(d.get("retired", False)),
                    full_sha256=d["full_sha256"],
                    normalized=d["normalized"],
                    shingles=frozenset(d["shingles"]),
                    shingle_words=d.get("shingle_words", SHINGLE_WORDS),
                )
            )
    return records


def retire_instance(manifest_path: Path, instance_id: str) -> bool:
    """Mark an instance retired (its content leaked); rewrite manifest atomically."""
    records = load_manifest(manifest_path)
    found = False
    for i, r in enumerate(records):
        if r.instance == instance_id and not r.retired:
            records[i] = replace(r, retired=True)
            found = True
    if found:
        tmp = manifest_path.with_suffix(".tmp")
        with tmp.open("w", encoding="utf-8") as fh:
            for r in records:
                fh.write(_line(r))
        tmp.replace(manifest_path)
    return found


def _append(manifest_path: Path, rec: InstanceRecord) -> None:
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    with manifest_path.open("a", encoding="utf-8") as fh:
        fh.write(_line(rec))


def _line(rec: InstanceRecord) -> str:
    d = {
        "instance": rec.instance,
        "seed": rec.seed,
        "created": rec.created,
        "retired": rec.retired,
        "full_sha256": rec.full_sha256,
        "normalized": rec.normalized,
        "shingles": sorted(rec.shingles),
        "shingle_words": rec.shingle_words,
    }
    return json.dumps(d, sort_keys=True) + "\n"
